# Generated by Django 4.2.6 on 2023-11-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='bid',
            field=models.ManyToManyField(related_name='bidListing', to='auctions.bids'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
