# Generated by Django 4.2.6 on 2024-01-20 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='content',
            new_name='thread_name',
        ),
    ]
