# Generated by Django 4.2.6 on 2024-01-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_content_messages_thread_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='receiver',
        ),
        migrations.AddField(
            model_name='messages',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
